//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web3.Pages
{


    public partial class _Default
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Web3.Pages.SiteMaster Master
        {
            get
            {
                return ((Web3.Pages.SiteMaster)(base.Master));
            }
        }
    }
}
